#- hosts: master
- hosts: nodes
  tasks:
  - name: Get token
    shell:  kubeadm token create --print-join-command
    register: token
    delegate_to: "{{ item }}"
    loop: "{{ groups['master']}}"
  - name: get facts from master
    setup:
    delegate_to: "{{ item }}"
    loop: "{{ groups['master']}}"
    delegate_facts: true
  - debug:
      msg: "{{ token }}"
  - name: Join Node
    shell: "{{ item  }}"
    with_items: "{{ token.results[0].stdout_lines }}"



